[package]
name = "serde_merge"
version = "0.1.0"
edition = "2018"
authors = ["Z4RX <iamz4rx@gmail.com>", "Dablus <Double125720@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/Z4RX/serde_merge"
readme = "README.md"

[dependencies]
anyhow = "1"
serde = "1"
serde_json = "1"
