name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2

      - name: Run cargo build
        run: cargo build

      - name: Run cargo test
        run: cargo test --verbose
